export const GOT_IT = 'GOT_IT';

export const PERIODS_FETCHED = 'PERIODS_FETCHED';
export const DISTRIBUTORS_FETCHED = 'DISTRIBUTORS_FETCHED';

export const UNRESOLVED_CUSTOMERS_FETCHED = 'UNRESOLVED_CUSTOMERS_FETCHED';
export const UNRESOLVED_CUSTOMERS3RD_FETCHED = 'UNRESOLVED_CUSTOMERS3RD_FETCHED';
